### ISSUE TITLE
Austria's app missing

### ISSUE THREAD

**Issue by jetzlstorfer** [iivanoo/covid-apps-observer#2]
In Austria we also have an app called "stop corona" https://www.roteskreuz.at/site/meet-the-stopp-corona-app/ 

Never tried it myself yet. But wanted to let you know. You'll find the links to the download in the link above.

**Comment by iivanoo** [comment]
Thanks Jurgen!
I just ran the analysis for Austria, you can find the results [here](https://github.com/iivanoo/covid-apps-observer/blob/master/data/data_at/reports/report_2020_5_11.md).
