### ISSUE TITLE
Extra app in the UK not found by your search

### ISSUE THREAD

**Issue by julianharty** [iivanoo/covid-apps-observer#3]
Ciao,
There's a very popular app in the UK for tracking COVID symptoms  https://play.google.com/store/apps/details?id=com.joinzoe.covid_zoe&gl=uk with over 1,000,000 installs and 80,000 reviews. The search query you're using (and even various searches I performed manually on the Google Play Web interface as I know the app exists) didn't find it. Please can you add it to your list. And as a suggestion there may well be other relevant apps you're yet to find. 

BTW: There's an online handbook called CoronaVirusTechHandbook (CVTH) https://coronavirustechhandbook.com/ and a community of people who support it and related projects. Perhaps there'll be ways you can share your respective work?

**Comment by julianharty** [comment]
There's also a very recently released app, subject to change, which the UK NHS are aiming to rollout across the country in a few days if the early tests (with 50K users so far) work https://play.google.com/store/apps/details?id=uk.nhs.nhsx.colocate&hl=en

**Comment by iivanoo** [comment]
Thanks Julian, indeed those apps are very interesting. 

Since the whole setup of the project is based on a country-by-country search using the web interface of Google Play, I will add add a new type of report for considering _apps suggested by the community_ which do not show up in the official search of Google Play.

**Comment by iivanoo** [comment]
Done. [Here](https://github.com/iivanoo/covid-apps-observer/blob/master/data/data_community/reports/report_2020_5_11.md) is the report for community-suggested apps.
