### ISSUE TITLE
Hunala

### ISSUE THREAD

**Issue by scottrkahler** [iivanoo/covid-apps-observer#4]
Hunala is an app, maybe outside of the scope of this scrapper, that can be used for contact tracing. https://hunala.yale.edu/

**Comment by iivanoo** [comment]
Hi @scottrkahler, thanks for the suggestion. I just added the Hunala app in the dataset.
You can find the results of the analysis [here](https://github.com/iivanoo/covid-apps-observer/blob/master/data/data_community/reports/report_2020_6_28.md#hunala).
